
" TEXT CONFIG
" set guifont=Fira\ Code:h11
set guifont=Consolas:h11
set encoding=utf-8

" INDENTATION
set autoindent
set smartindent
set smarttab
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
filetype indent on

" EDITOR
set nocompatible
set cursorline
set splitbelow splitright
set visualbell
set noerrorbells
set ttyfast
set lazyredraw
set showcmd
set showmode
set title
set wildmenu

set wildmode=longest:full,full
set t_Co=256
set colorcolumn=100
set laststatus=2
set scrolloff=3
set mouse=a

filetype plugin on

syntax on

" LINE NUMBERS, RULERS
set wrap
set linebreak
set number
set relativenumber
set ruler

" DISPLAY TABS AND TRAILING SPACES VISUALLY
set list listchars=tab:»·,trail:·,nbsp:·
set nojoinspaces

" SEARCH CONFIGURATIONS
set incsearch
set hlsearch
set ignorecase
set smartcase

" TURN OFF BACKUP
set nobackup
set noswapfile
set nowritebackup

" UNDO CONFIG
set undodir=~/.vim/undo
set undofile

source ~/.vim/_vimrc.plugins

" THEMES
set background=dark
let g:gruvbox_bold=0
let g:gruvbox_italic=0
colorscheme gruvbox

" KEY MAPPING
map <silent> <C-Tab> :bn<CR>
map <silent> <Leader>nt :NERDTreeFind<CR>
map <silent> <Leader>cc :NERDComToggleComment<CR>


